/*
 * sig_gen.c
 *
 *  Created on: Nov 11, 2025
 *      Author: mpari
 */


/*
 * Target: STM32L476 (TIM6 update → TRGO → DMA → DAC1_CH1)
 *
 * How it works:
 * 1) A small lookup table (100 samples) holds "One" period of the waveform (sine/square)
 * 2) TIM6 generates an "update" event at a fixed sample rate Fs (times per second)
 * 3) Each update triggers the DMA to move the next sample into the DAC register
 * 4) After 100 samples the DMA wraps around to the start (circular), so you get a periodic signal.
 * 		If Fs = 100 * Fout, the DAC outputs Fout Hz.
 *
 * 	User needs to change: waveform type and output frequency. Everything else runs in hardware (timer + DMA + DAC), so the CPU stays free.
*/


#include "7seg.h"			// For multiplexSegment() to show frequency
#include <string.h>
#include <ctype.h>
#include <math.h>			// For sinf
#include <stdio.h>
#include <ctype.h>
#include <SigGen.h>
#include "main.h"       	// For CubeMX-generated handles

// Assuming these handles are generated by CubeMX .. Please change handle names if required
extern TIM_HandleTypeDef htim6;        // TIM6
extern DAC_HandleTypeDef hdac1;        // DAC1 (we use CH1 - Outputting waveform on PA4)

// ----------------------------- Configuration ---------------------------------
#define SIG_WAVE_SAMPLES   100u            	// N samples per period
#define SIG_TIMER_CLK_HZ   80000000u       	// Could be same as System Clock, adjust if your TIM6 clock differs
#define SIG_FREQ_MIN_HZ    100u				// Freq range 100 - 9999 Hz
#define SIG_FREQ_MAX_HZ    9999u			// Freq range 100 - 9999 Hz
#define SIG_PSC            0u              	// prescaler (keep 0 for best resolution)

// ------------------------------ Module State ---------------------------------
static volatile uint32_t s_fout_hz = 1000u;     		// Current output frequency, default to 1000 Hz
static volatile sig_wave_t s_wave = SIG_WAVE_SINE;		// Current Output waveform, default to Sine
static uint16_t s_buf[SIG_WAVE_SAMPLES];        		// DMA source buffer
static bool s_started = false;							// Is TIM6 running?

// --------------------------- Helper functions ------------------------------


// ------------------------------ fill_sine() -----------------------------------
// Fill the buffer with one PERIOD of a 12-bit sine wave (0..4095).
// dst = destination array — where the function will store the generated sine wave samples
// n = number of samples per period
// -----------------------------------------------------------------------------------
static void fill_sine(uint16_t *dst, uint32_t n)
{
    // Base sine wave: y(i) = A sin(theta)
	// theta = 2*pi*i / N .. where N = SIG_WAVE_SAMPLES
	// Calculate sample values using this formula and store them in destination array
	for (uint32_t i = 0; i < n; ++i)
    {
        float theta = 2.0f * (float)M_PI * (float)i / (float)n;

        // map -1..1 -> 0..1
        // because DAC can't do negative..
        float s = (sinf(theta) * 0.5f) + 0.5f;

        dst[i] = (uint16_t)(s * 4095.0f + 0.5f);    // 12-bit range
    }
}

// ------------------------------ fill_square() -----------------------------------
// Fill the buffer with one PERIOD of a 12-bit Square wave (0..4095).
// dst = destination array — where the function will store the generated sine wave samples
// n = number of samples per period
// -----------------------------------------------------------------------------------
static void fill_square(uint16_t *dst, uint32_t n)
{
    // *** TO DO ***
    // Produce a 50% duty square wave using 12-bit values (0..4095)

	for(uint32_t i =0; i < n; ++i){
		if(i < n/2){
			dst[i] = (uint16_t)(4095.0f);
		}else{
			dst[i] = (uint16_t)(0.0f);
		}
	}


}


// ------------------------------ apply_waveform() -----------------------------------
// Copy the chosen waveform into the DMA buffer
// w = Waveform Type
// -----------------------------------------------------------------------------------
static void apply_waveform(sig_wave_t w)
{
    switch (w)
    {
		case SIG_WAVE_SINE:
			fill_sine(s_buf, SIG_WAVE_SAMPLES);
			break;

		case SIG_WAVE_SQUARE:
		    // *** TO DO ***
		    // Apply for Square Wave
			fill_square(s_buf,SIG_WAVE_SAMPLES);

			break;

		default:
			// Let's keep Sine as default waveform
			fill_sine(s_buf, SIG_WAVE_SAMPLES);
			break;
    }
}

// ------------------------------ Update_TIM6_fs() -----------------------------------
// Set TIM6 so its update rate equals the requested sample rate Fs
// Fs = sample_hz
// Calculate ARR using.. sample_hz = timer_clk / ((PSC+1)*(ARR+1))
// -----------------------------------------------------------------------------------
static void Update_TIM6_fs(uint32_t sample_hz)
{
	// Handle invalid Freq gracefully
	if (sample_hz == 0u)
	{
		// Override to 1
		sample_hz = 1u;
	}

	// *** TO DO ***
	
	// sample_hz = timer_clk / ((PSC+1)*(ARR+1))  => ARR = round(timer_clk/((PSC+1)*sample_hz)) - 1
	//
	// Calculate ARR
	// 		ARR = (timer_clk/Fs) - 1
	// 		Do Integer rounding
	// 		note: arr = (uint32_t)(value) -- this would truncate the decimal part so add 0.5 before converting to unsigned32 bit integer

	// Prevent underflow if calculation would go negative

	uint32_t timer_clk = HAL_RCC_GetPCLK1Freq();
	uint32_t prescaler = TIM6->PSC;
	uint32_t ARR = round(timer_clk/((prescaler)*sample_hz)) - 1;
	uint32_t counter = 0;




	// *** TO DO ***
    // Now we can update TIM6
    //		Pause timer or Disable  -- htim6
    // 		Set Prescaler	-- SIG_PSC;
    //		Set ARR 	-- arr
    //		Set counter value - recommending to set to zero .. This would keep output waveform phase-aligned
    //  	Clear timer flags - TIM_FLAG_UPDATE
    //		Enable Timer	-- htim6
	//
	// Hint: Use macros/functions defined in stm32l4xx_hal_tim.h 

	__HAL_TIM_DISABLE(&htim6);
	__HAL_TIM_SET_PRESCALER(&htim6, prescaler);
	__HAL_TIM_SET_COUNTER(&htim6, counter);
	__HAL_TIM_SET_AUTORELOAD(&htim6, ARR);
	 __HAL_TIM_CLEAR_FLAG(&htim6, TIM_FLAG_UPDATE);
	 __HAL_TIM_ENABLE(&htim6);


}

// ------------------------------ apply_frequency() -----------------------------------
// Given desired output frequency (Fout), compute Sample rate/Fre
// 		Fs = N*Fout and update TIM6 accordingly
// -----------------------------------------------------------------------------------
static void apply_frequency(uint32_t fout_hz)
{
    // Ensure desired output Freq is within valid range
	if (fout_hz < SIG_FREQ_MIN_HZ)
    	fout_hz = SIG_FREQ_MIN_HZ;

    if (fout_hz > SIG_FREQ_MAX_HZ)
    	fout_hz = SIG_FREQ_MAX_HZ;

    // sample rate/freq = N * Fout
    uint32_t Fs = fout_hz * SIG_WAVE_SAMPLES;

    // Update TIM6
    Update_TIM6_fs(Fs);
}

// ------------------------------ Public API -----------------------------------

// ------------------------------ SigGen_Init() -----------------------------------
// Initialize SigGen Utility
// 		Apply default waveform and Freq
//		Start DAC and set up DMA with Buffer used to generate output signal
// -----------------------------------------------------------------------------------
void SigGen_Init(void)
{
    // Default buffer = sine
    apply_waveform(SIG_WAVE_SINE);

    // Start DAC and prime DMA in circular mode.
    // Note: Timer can be started/stopped separately.
    HAL_DAC_Start(&hdac1, DAC_CHANNEL_1);
    HAL_DAC_Start_DMA(&hdac1, DAC_CHANNEL_1, (uint32_t*)s_buf, SIG_WAVE_SAMPLES, DAC_ALIGN_12B_R);

    // Configure initial Fs from s_fout_hz
    apply_frequency(s_fout_hz);

    // We will not start timer automatically, it can be done separately
}

// ------------------------------ SigGen_Start() -----------------------------------
// Start Signal Generation
// 		Apply Current Output Freq and Kickoff TIM6 to start generating signal
//		Note: TIM6 TRGO will clock DAC DMA
// -----------------------------------------------------------------------------------
void SigGen_Start(void)
{
    if (!s_started)
    {
        // Ensure ARR/PSC are already set to current frequency
        apply_frequency(s_fout_hz);
        HAL_TIM_Base_Start(&htim6);
        s_started = true;
    }
}

// ------------------------------ SigGen_Start() -----------------------------------
// Stop/Pause Signal Generation
// 		Stop TIM6
//
// -----------------------------------------------------------------------------------
void SigGen_Stop(void)
{
    if (s_started)
    {
        HAL_TIM_Base_Stop(&htim6);
        s_started = false;
    }
}

// ------------------------------ SigGen_Set() -----------------------------------
// Set desired Waveform type and Out Freq
//
// -----------------------------------------------------------------------------------
bool SigGen_Set(sig_wave_t wave, uint32_t fout_hz)
{
    // Ensure Freq value is within range
	if (fout_hz < SIG_FREQ_MIN_HZ || fout_hz > SIG_FREQ_MAX_HZ)
        return false;

    // Update current Waveform and Out Freq values
    s_wave = wave;
    s_fout_hz = fout_hz;

    //Check if TIM6 is started already, if so we need to Stop Signal Generation, Update values and then restart signal generation
    if (s_started)
    {
    	SigGen_Stop();
    }
	apply_waveform(s_wave);
	apply_frequency(s_fout_hz);
	SigGen_Start();

    return true;
}

// ------------------------------ SigGen_ParseCommand() -----------------------------------
// Parse Command
// Command format: <Waveform Type><Space><Freq in Hz>
// If command is valid then set Signal Generation and Update Multisegment Display
// -----------------------------------------------------------------------------------
bool SigGen_ParseCommand(const char *cmd)
{
    if (!cmd) return false;

	char wf[16] = {0};
	unsigned freq = 0;

	// parse: <word> <number>  (ignores extra spaces at start)
	if (sscanf(cmd, " %15s %u", wf, &freq) != 2) return false;
	if (freq < SIG_FREQ_MIN_HZ || freq > SIG_FREQ_MAX_HZ) return false;

	// case-insensitive check of waveform token
	char a = (char)tolower((unsigned char)wf[0]);
	char b = (char)tolower((unsigned char)wf[1]);  // may be '\0'

	sig_wave_t waveform;
	if (a == 's' && b == 'i')         waveform = SIG_WAVE_SINE;     // "sine"
	else if (a == 's' && b == 'q')    waveform = SIG_WAVE_SQUARE;   // "square"
	else if (wf[0] == '0')            waveform = SIG_WAVE_SINE;     // optional numeric - just for fun :)
	else if (wf[0] == '1')            waveform = SIG_WAVE_SQUARE;
	else return false;

	if ( SigGen_Set(waveform, (uint32_t)freq) )
	{
	   multiplexSegment(freq);
	   return true;
	}
	else
	   return false;
}
